DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS transacctions;
DROP TABLE IF EXISTS users_transactions;

CREATE TABLE users(
id INTEGER PRIMARY KEY AUTO_INCREMENT,
userID VARCHAR(9)
);

INSERT INTO users(userID) VALUES("655784396")